version: "3"
services:
  userapi:
    image: finalusersapi
    build: .
    ports:
      - "8080:8080"
    environment:
       DATABASE_URL: jdbc:postgresql://postgres:5432/test
       DATABASE_USERNAME: postgres
       DATABASE_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - custom_network
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge