version: "3"
services:
  userapi:
    image: finalusersapi
    build: .
    ports:
      - "8080:8080"
    environment:
       DATABASE_URL: jdbc:postgresql://postgres:5432/test
       DATABASE_USERNAME: postgres
       DATABASE_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - custom_network
    volumes:
      - userapi_data:/app/data
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - custom_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

networks:
  custom_network:
    driver: bridge
volumes:
  userapi_data:
  postgres_data: